### ISSUE TITLE
B3 changed format of compressed files (.zip to 7zip)

### ISSUE THREAD

**Issue by msperlin** [msperlin/GetHFData#10]
- read fct cant read compressed files
- need to install 7zip in host computer (will CRAN accept it?)

**Comment by anselmoaraujo** [comment]
You can work with the package 'archive' with no need to install 7zip locally.

**Comment by msperlin** [comment]
Thankyou, I'll have a look in archive.

**Comment by msperlin** [comment]
Just fixed it in the latest update. Reinstall with devtools::install_github('msperlin/GetHFData' and it should work.

best,
