### ISSUE TITLE
Erro de leitura dos arquivos

### ISSUE THREAD

**Issue by rodriguesra** [msperlin/GetHFData#11]
Quando eu tento rodar o exemplo do README, recebo a seguinte mensagem de erro:

Running ghfd_get_HF_Data for:
   type.market = equity
   type.data = trades
   my.assets = PETR	VALE
   type.output = agg
      agg.diff = 15 min
Reading ftp contents for equity(trades) (attempt = 1|10)
   Found  154  files in ftp
   First available date in ftp:  2019-11-01
   Last available date in ftp:   2020-06-09
   First date to download:  2020-06-01
   Last date to download:   2020-06-09
Downloading ftp files/NEG_20200601.7z (1|7) Attempt 1
   -> Reading filesError in read_tokens_(data, tokenizer, col_specs, col_names, locale_,  : 
  embedded nul in string: '\0O\xe2\xfe\x870\xa7\x9e&\xbfk\xf72\xe3fd\xde('

Alguma ideia de como posso contornar isso?

**Comment by msperlin** [comment]
Oi Rodrigo,

Instale a versão do github e tente novamente. A versão do CRAN deve ser removida em breve, infelizmente.
