### ISSUE TITLE
B3 new source of data for HF

### ISSUE THREAD

**Issue by Lvitor** [msperlin/GetHFData#13]
Hi Marcelo, 
This address http://www.b3.com.br/pt_br/market-data-e-indices/servicos-de-dados/market-data/cotacoes/cotacoes/
have file with informatio for HF trading.

see ya.

**Comment by msperlin** [comment]
Thanks Leornardo,

Yes, I'm aware of the "new ftp". However, the data is shallow (10 trading days) for any research setup. 
Sorry this change is not priority right now.

best,
