### ISSUE TITLE
Aggregate the number of buys and sells

### ISSUE THREAD

**Issue by lemuelemos** [msperlin/GetHFData#3]
Hi Perlin, i has suggested a change to summarise in agg output for show the number of buys and sells quantity that a use to order flow analysis. I made this change in my code cloning you repo, but i have to compile every time that i will use this function, so a suggested to do natively by package. Sorry to not open a issue before, but i wanna know if you agree this change. Tks.

**Comment by msperlin** [comment]
Hi Lemuelemos,

I'm not sure if it its necessary to add it to the package. It already summarises buys and sells according to a chosen time bin (e.g. 15 minutes). 

Best,

**Comment by lemuelemos** [comment]
The problem is that the number of sells and buys is not informative, the quantity is more important to price formation. But ok, only a suggestion.

**Comment by msperlin** [comment]
Ok, thanks.
