### ISSUE TITLE
agg.diff = '1 day'

### ISSUE THREAD

**Issue by CWbtc** [msperlin/GetHFData#4]
-> Processing file - Found 3 lines for 1 selected tickersError in cut.default(unclass(x), unclass(breaks), labels = labels, right = right,  : 
  'breaks' are not unique

**Comment by msperlin** [comment]
Please post the full code. Otherwise I can't see what may be the problem.

**Comment by meumesmo** [comment]
Dear msperlin, getting the following error when using gethfdata:: ghfd_get_HF_data()

my.fg <- GetHFData::ghfd_get_HF_data(ticker,
                                     type.market = my.type.market,
                                     first.date = last.date,
                                     last.date = last.date,
                                     first.time = '10:00:00',
                                     last.time = '17:00:00',
                                     type.output = 'agg',
                                     agg.diff = '5 min')


Downloading ftp files/NEG_20200604.7z (1|1) Attempt 1 - File exists, skipping dl
   -> Reading filesError in read_tokens_(data, tokenizer, col_specs, col_names, locale_,  : 
  cadeia de caracteres com nul incluso: ''

**Comment by msperlin** [comment]
Please post the full, reproducible, code. Otherwise I can't help you..

**Comment by meumesmo** [comment]
> Please post the full, reproducible, code. Otherwise I can't help you..

library(GetHFData)
library(tidyverse)
library(dplyr)

ticker <- c('PETR4', 'GGBR4')

my.type.market <- 'equity'

last.date <- '2020-06-04'

my.fg <- GetHFData::ghfd_get_HF_data(ticker,
                                     type.market = my.type.market,
                                     first.date = last.date,
                                     last.date = last.date,
                                     first.time = '10:00:00',
                                     last.time = '17:00:00',
                                     type.output = 'agg',
                                     agg.diff = '5 min')

thanks

**Comment by msperlin** [comment]
It is working fine with the latest version:

Running ghfd_get_HF_Data for:
   type.market = equity
   type.data = trades
   my.assets = PETR4	GGBR4
   type.output = agg
      agg.diff = 5 min
Reading ftp contents for equity(trades) (attempt = 1|10)
   Found  151  files in ftp
   First available date in ftp:  2019-11-01
   Last available date in ftp:   2020-06-04
   First date to download:  2020-06-04
   Last date to download:   2020-06-04
Downloading ftp files/NEG_20200604.7z (1|1) Attempt 1
   -> Reading files - Imported  3461167 lines, 711 unique tickers
   -> Processing file - Found 111405 lines for 2 selected tickers
   -> Aggregation resulted in dataframe with 162 rows

Please install the latest version: 
`devtools::install_github("msperlin/GetHFData")`
