### ISSUE TITLE
Change in filenames ?

### ISSUE THREAD

**Issue by msperlin** [msperlin/GetHFData#5]
Pelo que deu a entender, isso aconteceu porque, aparentemente, a B3 mudou o método de compressão de zip para gz.

Acredito que modificando a linha 40 e 43 da função ghfd_get_ftp_contents para:

    if (type.data == "trades") {
      pattern.files <- "NEG_(.*)"
    }
    else if (type.data == "orders") {
      pattern.files <- "OFER_(.*)"
    }

Isso deixe de ser um problema.

**Comment by guilhermebodin** [comment]
Olá Marcelo, 
Não seria da linha 64 a 69? Onde atualmente é 
```R
if (type.data =='trades'){
      # filter ftp files for trades
      pattern.files <- 'NEG_(.*?).zip'
    } else if (type.data == 'orders') {
      pattern.files <- 'OFER_(.*?).zip'
    }
 ```

**Comment by msperlin** [comment]
Ok, aceitei o pull request. Estou testando aqui e a principio tudo Ok.

**Comment by guilhermebodin** [comment]
Obrigado, o código da nova versão é atualizado no CRAN automaticamente?

**Comment by msperlin** [comment]
Nao, estou encaminhando hoje mesmo. Amanha deve estar no CRAN.

**Comment by guilhermebodin** [comment]
Obrigado! 😁
